### ISSUE TITLE
Require nodejs version ^4.0.0, current v5.3.0

### ISSUE THREAD

**Issue by shenggen1987** [uxcore/starter-kit#3]
怎么提示我node版本太高啦？

**Comment by gbk** [comment]
因为目前发现 nowa 插件的一些依赖对 nodejs 5.x 和 6.x 的兼容存在问题，所以仅支持 4.x 版本。
- 5.x 下 npminstall 频发堆栈溢出问题，
- 6.x 下 stylus-loader 有个 bug，导致报错 https://github.com/nowa-webpack/nowa/issues/8

等待所有外部问题解决，我们也会支持新版本的 nodejs！
